// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission08_Group07.Models;

namespace Mission08_Group07.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20230224221901_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission08_Group07.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission08_Group07.Models.NewTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuadrantNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            CategoryID = 1,
                            Completed = false,
                            DueDate = new DateTime(2023, 2, 25, 15, 19, 0, 875, DateTimeKind.Local).AddTicks(4594),
                            QuadrantNumber = 1,
                            Task = "Clean dishes"
                        },
                        new
                        {
                            TaskID = 2,
                            CategoryID = 2,
                            Completed = false,
                            DueDate = new DateTime(2023, 2, 27, 15, 19, 0, 877, DateTimeKind.Local).AddTicks(9730),
                            QuadrantNumber = 2,
                            Task = "Go for a run"
                        },
                        new
                        {
                            TaskID = 3,
                            CategoryID = 3,
                            Completed = false,
                            DueDate = new DateTime(2023, 2, 26, 15, 19, 0, 878, DateTimeKind.Local).AddTicks(465),
                            QuadrantNumber = 3,
                            Task = "Read a book"
                        },
                        new
                        {
                            TaskID = 4,
                            CategoryID = 4,
                            Completed = false,
                            DueDate = new DateTime(2023, 2, 28, 15, 19, 0, 878, DateTimeKind.Local).AddTicks(900),
                            QuadrantNumber = 4,
                            Task = "Call a friend"
                        });
                });

            modelBuilder.Entity("Mission08_Group07.Models.NewTask", b =>
                {
                    b.HasOne("Mission08_Group07.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
